version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: shyam
      PORT: 5000
      DB_HOST_PSQL: db
      DB_USER_PSQL: shyam
      DB_PASS_PSQL: shyam
      DB_NAME_PSQL: restaurants
    volumes:
      - ./backend:/backend
    command: sh -c "rails db:migrate && rm /backend/tmp/pids/server.pid && rails s -b 0.0.0.0 -p 5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    restart: always
    environment:
      PORT: 8000
      BROWSER: none
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm start"

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: shyam
      POSTGRES_PASSWORD: shyam
      POSTGRES_DB: restaurants
    # volumes:
    # - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass shyam
    volumes:
      - redis_data:/data

volumes:
#   postgres_data:
  redis_data: