version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: restaurant_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: restaurant
    volumes:
      - ./backup:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro

  php:
    image: php:8.0-apache
    container_name: restaurant_php
    restart: always
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./apache2.conf:/etc/apache2/apache2.conf:ro
    depends_on:
      - mysql