name: Rails RSpec Tests

on:
  pull_request:
    branches:
      - main # Change to your main branch name

jobs:
  rspec:
    name: Run RSpec Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_DB: restaurants
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: create env
        run: cp ./backend/.env.sample ./backend/.env

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Cache Bundler dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Dependencies
        run: bundle install
        working-directory: ./backend

      - name: Database Setup
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
        working-directory: ./backend

      - name: Run RSpec Tests
        run: bundle exec rspec
        working-directory: ./backend
