name: Rails RSpec Tests

on:
  pull_request:
    branches:
      - main # Change to your main branch name

jobs:
  rspec:
    name: Run RSpec Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: restaurants_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DB_HOST_PSQL: localhost
          DB_NAME_PSQL: restaurants_test
          DB_USER_PSQL: postgres
          DB_PASS_PSQL: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install Dependencies
        run: |
          cd backend
          bundle install --jobs 4 --retry 3

      - name: Database Setup
        run: |
          cd backend
          bundle exec rake db:create db:migrate RAILS_ENV=test DB_HOST=${{ services.postgres.env.DB_HOST_PSQL }} DB_NAME=${{ services.postgres.env.DB_NAME_PSQL }} DB_USER=${{ services.postgres.env.DB_USER_PSQL }} DB_PASSWORD=${{ services.postgres.env.DB_PASS_PSQL }}

      - name: Run RSpec Tests
        run: |
          cd backend
          bundle exec rspec
